language: node_js
node_js:
  - "7"
env:
  - SKIP_PREFLIGHT_CHECK=true
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
before_script:
  - npm install
branches:
  only:
    - develop
    - master
