name: ESLint
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - name: set up node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: check out code
        uses: actions/checkout@v2
      - name: install
        run: yarn install
      - name: eslint
        run: yarn lint
